title = "config file for MariaDB"

# Database Info
[database-ubuntu]
DATABASE = '[db]'
#HOST = '192.168.0.x'
HOST = 'ubuntu.local'
PASSWORD = '[pw]'
PORT = 3306
TABLE = '[table]'
USER = '[user]'

[database-mac]
DATABASE = '[db]'
HOST = 'localhost'
PASSWORD = '[pw]'
PORT = 3306
TABLE = '[table]'
USER = '[user]'
